name: CI/CD Pipeline

on:
  push:
    branches: [gargeya]
  pull_request:
    branches: [gargeya]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 src api --count --select=E9,F63,F7,F82 --show-source --statistics

  docker-build-push:
    needs: build-test-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOC_USER }}
          password: ${{ secrets.DOC_PASS }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOC_USER }}/mlops-app:latest .
          docker push ${{ secrets.DOC_USER }}/mlops-app:latest
